<?php

namespace Database\Seeders;

use App\Models\Payslip;
use Illuminate\Database\Seeder;

class PayslipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (!Payslip::find(1)) {
            Payslip::insert([
                [
                    'emp_code' => '2',
                    'month' => '2021-08-01',
                    'department' => '1',
                    'full_name' => 'satoshi nakamoto',
                    'working_days' => 18.5,
                    'working_out_of_days' => 3.5,
                     'special_leave_days' => 1,
                    'paid_off_days' => 1,
                    'off_days' => 2,
                    'remaining_paid_off_days' => 18.5,
                    'working_time' => 8,
                    'late_early' => 1,
                    'common_ot' => 0,
                    'hard_work_time_2' => 5,
                    'midnight_cp_time' => 1500000,
                    'basic_salary' => 3000000,
                    'salary_for_performance' => 2000000,
                    'position_cp' => 1,
                    'heavy_truck_cp' => 2,
                    'bd_cp' => 0,
                    'other_cp' => 0,
                    'ot_salary_cp' => 0,
                    'hard_work_2_cp' => 0,
                    'midnight_cp' => 1.5,
                    'paid_off_adjustment' => 1000000,
                    'ot_cp_adjustment' => 0,
                    'last_month_adjustment' => 200,
                    'adjusted_salary' => 1000000,
                    'bounty' => 500,
                    'attendance_deduction' => 0,
                    'other_payment_paid_off' => 0,
                    'ot_adjustment_cp' => 0,
                    'reduced_amount' => 0,
                    'taxable_amount' => 10,
                    'transportation_cp' => 500,
                    'total_amount_of_payment' => 2000000,
                    'health_insurance' => 300,
                    'nursing_care_insurance' => 200,
                    'welfare_pension_insurance' => 500,
                    'unemployment_insurance' => 1000000,
                    'total_insurance_amount' => 2500000,
                    'inhabitant_tax' => '0',
                    'inhabitant_tax_deduction' => 0,
                    'apartment_fee' => 0,
                    'other_1' => 0,
                    'other_2' => 0,
                    'other_3' => 0,
                    'incurred_previous_month' => 0,
                    'advance_paid' => 0,
                    'withholding' => 0,
                    'adjustment_deduction' => 0,
                    'year_end_adjustment' => 0,
                    'total_dedution_amount' => 1500000,
                    'payable_overpaid_tax' => 600000,
                    'net_payment' => 0,
                    'cash_salary' => 3000000,
                    'tranfer_amount_１' => 9000000
                ],
                [
                    'emp_code' => '888888',
                    'month' => '2021-08-01',
                    'department' => '1',
                    'full_name' => 'pigion nakamoto',
                    'working_days' => 22.5,
                    'working_out_of_days' => 2.5,
                     'special_leave_days' => 2,
                    'paid_off_days' => 1,
                    'off_days' => 2,
                    'remaining_paid_off_days' => 18.5,
                    'working_time' => 18,
                    'late_early' => 1,
                    'common_ot' => 0,
                    'hard_work_time_2' => 5,
                    'midnight_cp_time' => 1500000,
                    'basic_salary' => 3000000,
                    'salary_for_performance' => 2000000,
                    'position_cp' => 1,
                    'heavy_truck_cp' => 2,
                    'bd_cp' => 0,
                    'other_cp' => 0,
                    'ot_salary_cp' => 0,
                    'hard_work_2_cp' => 0,
                    'midnight_cp' => 1.5,
                    'paid_off_adjustment' => 1000000,
                    'ot_cp_adjustment' => 0,
                    'last_month_adjustment' => 200,
                    'adjusted_salary' => 1000000,
                    'bounty' => 500,
                    'attendance_deduction' => 0,
                    'other_payment_paid_off' => 0,
                    'ot_adjustment_cp' => 0,
                    'reduced_amount' => 0,
                    'taxable_amount' => 10,
                    'transportation_cp' => 500,
                    'total_amount_of_payment' => 2000000,
                    'health_insurance' => 300,
                    'nursing_care_insurance' => 200,
                    'welfare_pension_insurance' => 500,
                    'unemployment_insurance' => 1000000,
                    'total_insurance_amount' => 2500000,
                    'inhabitant_tax' => '0',
                    'inhabitant_tax_deduction' => 0,
                    'apartment_fee' => 0,
                    'other_1' => 0,
                    'other_2' => 0,
                    'other_3' => 0,
                    'incurred_previous_month' => 0,
                    'advance_paid' => 0,
                    'withholding' => 0,
                    'adjustment_deduction' => 0,
                    'year_end_adjustment' => 0,
                    'total_dedution_amount' => 1500000,
                    'payable_overpaid_tax' => 600000,
                    'net_payment' => 0,
                    'cash_salary' => 3000000,
                    'tranfer_amount_１' => 20000000
                ],
                [
                    'emp_code' => '888888',
                    'month' => '2021-07-01',
                    'department' => '2',
                    'full_name' => 'pigion nakamoto',
                    'working_days' => 16.5,
                    'working_out_of_days' => 5.5,
                    'special_leave_days' => 5,
                    'paid_off_days' => 1,
                    'off_days' => 2,
                    'remaining_paid_off_days' => 185,
                    'working_time' => 18,
                    'late_early' => 1,
                    'common_ot' => 0,
                    'hard_work_time_2' => 5,
                    'midnight_cp_time' => 1500000,
                    'basic_salary' => 3000000,
                    'salary_for_performance' => 2.000,
                    'position_cp' => 1,
                    'heavy_truck_cp' => 2,
                    'bd_cp' => 0,
                    'other_cp' => 0,
                    'ot_salary_cp' => 0,
                    'hard_work_2_cp' => 0,
                    'midnight_cp' => 1.5,
                    'paid_off_adjustment' => 1000000,
                    'ot_cp_adjustment' => 0,
                    'last_month_adjustment' => 200,
                    'adjusted_salary' => 1000000,
                    'bounty' => 500,
                    'attendance_deduction' => 0,
                    'other_payment_paid_off' => 0,
                    'ot_adjustment_cp' => 0,
                    'reduced_amount' => 0,
                    'taxable_amount' => 10,
                    'transportation_cp' => 500,
                    'total_amount_of_payment' => 2000000,
                    'health_insurance' => 300,
                    'nursing_care_insurance' => 200,
                    'welfare_pension_insurance' => 500,
                    'unemployment_insurance' => 1000000,
                    'total_insurance_amount' => 2500000,
                    'inhabitant_tax' => '0',
                    'inhabitant_tax_deduction' => 0,
                    'apartment_fee' => 0,
                    'other_1' => 0,
                    'other_2' => 0,
                    'other_3' => 0,
                    'incurred_previous_month' => 0,
                    'advance_paid' => 0,
                    'withholding' => 0,
                    'adjustment_deduction' => 0,
                    'year_end_adjustment' => 0,
                    'total_dedution_amount' => 1500000,
                    'payable_overpaid_tax' => 600000,
                    'net_payment' => 0,
                    'cash_salary' => 3000000,
                    'tranfer_amount_１' => 9000000
                ],
            ]);
        }
    }
}
